In [1]:
import pandas as pd
import numpy as np

In [3]:
rb_2022_df = pd.read_csv('datasets/ukr_rus_ir_all_bridge_relay_2011-2022.csv')

In [4]:
rb_2021_df = pd.read_csv('datasets/ukr_rus_ir_all_bridge_relay_2020-2021.csv')

In [12]:
rb_2021_2022_df = pd.concat([rb_2021_df, rb_2022_df]).reset_index().drop(columns=['index'])
rb_2021_2022_df

,date,users_bridge_ukr,users_relay_ukr,users_br_perc_ukr,users_bridge_rus,users_relay_rus,users_br_perc_rus,users_bridge,users_relay,users_br_perc,users_bridge_ir,users_relay_ir,users_br_perc_ir
0,2020-12-27,635,49319,1.271169,8223,335037,2.395560,37592,2244586,1.647198,5467,28107,16.283434
1,2020-12-28,642,50568,1.253661,8349,343418,2.373446,38468,2326926,1.626283,5407,33157,14.020848
2,2020-12-29,689,49571,1.370871,8982,343044,2.551516,40258,2318827,1.706509,5463,36697,12.957780
3,2020-12-30,701,48786,1.416534,9406,341685,2.679078,40872,2271025,1.767899,5306,36272,12.761557
4,2020-12-31,624,45661,1.348169,8820,311808,2.750851,38128,2131874,1.757049,4705,34314,12.058228
...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,2022-05-21,959,37308,2.506076,35473,105156,25.224527,70625,2979390,2.315562,2167,11659,15.673369
295,2022-05-22,936,36490,2.500935,35968,106178,25.303561,71623,2868764,2.435836,2133,11504,15.641270
296,2022-05-23,1041,37653,2.690340,35095,110308,24.136366,71856,2740249,2.555239,2116,10909,16.245681
297,2022-05-24,999,35871,2.709520,36885,109437,25.208103,71296,2745070,2.531489,1901,10561,15.254373
298,2022-05-25,1020,38280,2.595420,34811,117658,22.831526,72251,3204463,2.204983,2131,10776,16.510421

In [13]:
rb_2021_2022_df.date = pd.to_datetime(rb_2021_2022_df.date, format='%Y-%m-%d')

In [14]:
rb_2021_2022_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               299 non-null    datetime64[ns]
 1   users_bridge_ukr   299 non-null    int64
 2   users_relay_ukr    299 non-null    int64
 3   users_br_perc_ukr  299 non-null    float64
 4   users_bridge_rus   299 non-null    int64
 5   users_relay_rus    299 non-null    int64
 6   users_br_perc_rus  299 non-null    float64
 7   users_bridge       299 non-null    int64
 8   users_relay        299 non-null    int64
 9   users_br_perc      299 non-null    float64
 10  users_bridge_ir    299 non-null    int64
 11  users_relay_ir     299 non-null    int64
 12  users_br_perc_ir   299 non-null    float64
dtypes: datetime64[ns](1), float64(4), int64(8)
memory usage: 30.5 KB

In [16]:
rb_2021_2022_df['year'] = rb_2021_2022_df['date'].dt.year
rb_2021_2022_df['month'] = rb_2021_2022_df['date'].dt.month

In [19]:
year_month_grouped = rb_2021_2022_df.groupby(['year', 'month'], as_index=False).agg('mean')
year_month_grouped

,year,month,users_bridge_ukr,users_relay_ukr,users_br_perc_ukr,users_bridge_rus,users_relay_rus,users_br_perc_rus,users_bridge,users_relay,users_br_perc,users_bridge_ir,users_relay_ir,users_br_perc_ir
0,2020,12,658.200000,48781.000000,1.332081,8756.000000,334998.400000,2.550090,39063.600000,2.258648e+06,1.700988,5269.600000,33709.400000,13.616369
1,2021,1,660.964286,56268.142857,1.187337,8669.714286,347128.857143,2.447279,39715.071429,2.355043e+06,1.690735,4007.464286,35793.714286,10.102565
2,2021,2,672.892857,54638.678571,1.218856,9462.071429,334450.035714,2.764507,43299.428571,2.188064e+06,1.945388,3521.035714,35124.500000,9.125581
3,2021,3,723.129032,52273.741935,1.370171,9691.838710,322587.161290,2.921679,45360.096774,2.124132e+06,2.093639,3098.161290,29471.580645,9.493082
4,2021,4,724.200000,48291.933333,1.481134,10243.833333,316854.866667,3.136187,45903.500000,2.150187e+06,2.098219,3338.100000,31037.733333,9.745174
5,2021,5,660.142857,43979.964286,1.479399,9961.964286,300017.892857,3.219372,46025.464286,2.092964e+06,2.153397,3275.035714,30122.142857,9.845901
6,2021,12,661.000000,40550.800000,1.605414,36786.800000,186284.800000,16.495364,79490.200000,2.478837e+06,3.109491,3085.800000,11349.600000,21.373418
7,2022,1,696.066667,39303.800000,1.744593,35032.233333,172932.166667,16.812988,76047.033333,2.446617e+06,3.022363,2940.633333,11436.733333,20.368548
8,2022,2,765.607143,57138.000000,1.473052,32229.678571,151608.142857,17.815096,70880.821429,2.462644e+06,2.795426,2367.714286,11231.214286,17.424473
9,2022,3,914.709677,56912.225806,1.661516,43160.096774,131300.387097,24.776134,83322.677419,2.348763e+06,3.433512,1974.193548,10223.161290,16.204570
10,2022,4,837.100000,38827.900000,2.112526,36552.200000,100936.900000,26.538205,73075.866667,2.349579e+06,3.025701,1988.700000,9866.866667,16.777130
11,2022,5,977.280000,37121.000000,2.569608,34469.640000,100884.040000,25.506145,69986.560000,2.566775e+06,2.678896,2127.520000,10195.960000,17.224980

In [20]:
year_month_grouped.to_csv('relay_bridge_2020-2022_group_year_month.csv', index=False)